### ISSUE TITLE
example/civic.coconut does not build anymore. 

### ISSUE THREAD

**Issue by leegbestand** [leegbestand/coconut#11]
error: Duplicate name '' in values of enum '�'
        int, float, bool, void
                          ^~~~
civic.coconut:48:9: note: Previously declared here
        int, float, bool, void

Andcivic.coconut:298:37: note: Lifetime that is being conflicted with.
        BinOpEnum op { constructor, mandatory, disallowed = {and, or}}

**Comment by rickteuthof** [comment]
I suspect there's an id not handled properly in check.c. Will fix this ASAP.

Did you test this with the typed backend?

**Comment by leegbestand** [comment]
No, I tested it with the dynamic backend, but it fails before it reaches the backend. Ah, id sounds possible.

**Comment by rickteuthof** [comment]
I'm unable to replicate the bug, but it could be undefined behaviour somewhere.

**Comment by leegbestand** [comment]
I likely had a corrupted version. Can not reproduce it either.

**Comment by leegbestand** [comment]
I get it sometimes and sometimes not. 
check.c:624
            :597 
And some other locations seem to print the id instead of a char?

**Comment by leegbestand** [comment]
This happens because in the parser, idlist exists out of ids and to make it and actual ID makes sense. However, enumvalues and some other things(lifetimes) also use the idlist, because ids used to be char*. For enumvalues we probably want the ID type, but for lifetimes we probably want a stringlist in the parser.

**Comment by rickteuthof** [comment]
We could change all occurrences of strings in those entities into Ids as well, and then adapt the code accordingly. They would simply have to take the ->orig member of the id. I haven't personally tested the code with lifetimes so that's why it doesn't work as of now.

**Comment by leegbestand** [comment]
That is probably the least amount of work, so sounds good.

**Comment by rickteuthof** [comment]
Issue should be fixed, lifetimes don't use Ids as that's not necessary for code generation.
