### ISSUE TITLE
Relative include dirs

### ISSUE THREAD

**Issue by leegbestand** [leegbestand/coconut#12]
In the merge_backends, copra has relative include directories, which is rather error-prone. It would be better to have absolute ones and let the compiler find them via -I.

**Comment by leegbestand** [comment]
This also breaks the option to specify include and source directories where the code should be generated. Not sure if we should still support it.

**Comment by rickteuthof** [comment]
That's true, i'm not sure what the best solution is in this case. We could combine copra and generated into one big directory but i'm not sure if that would be the most elegant solution.

**Comment by leegbestand** [comment]
Thats not needed, we just need one layer that is constant, the rest can be achieved with specifying include directories to the compiler or via cmake. So, probably place all generated headers in a directory named 'ccngen' and all copra includes in 'ccn'. Then it is also clearer where headers come from for the user. So, just add a directory in the include dir of copa and add all headers to to it. And for the generated the inlcude dir should always have ccngen as the last entry.

**Comment by rickteuthof** [comment]
So if i understand correctly, the directory layout should be as follows:

```
copra
| - source files
| - ccn
| | - core includes
| - ccngen
| | - generated includes
```

**Comment by leegbestand** [comment]
My idea was to have the following
```
copra/
| - src/  
| - include/ccn/
generated/
| - src/
| - include/ccngen/
```
Then you can specify the include dirs generated/include and copra/include in your CMakeLists but also provides the option to use different directories, as long as they have a ccn/ and ccngen/ dir containing the required includes.

**Comment by rickteuthof** [comment]
This structure is now pushed to merge_backends and should work, if there's anything you'd like to change please let me know.
