### ISSUE TITLE
For the phase driver to work, the dynamic backend phase driver should be removed. 

### ISSUE THREAD

**Issue by leegbestand** [leegbestand/coconut#14]
The couple functions in the dynamic backend now collide with the phase driver(branch: merge_phase_driver). 

If those are removed the phase driver works with the dynamic backend(excluding sub-roots). 

NOTE: 
For now, I have only tested simple.ccn.

**Comment by rickteuthof** [comment]
What functions are your referring to? There's still a gen-action-handling file in the dynamic backend which can be safely removed (as it was a copy of the static one anyway)

**Comment by leegbestand** [comment]
Ah thanks, I will look at that. It is about the phase_start phase_error functions and the phase_vtable. But deleting them seems to be safe.

**Comment by rickteuthof** [comment]
Ah yes, i understand what you mean, i assume the phase vtable isn't necessary anymore since that's handled by the phase driver.

**Comment by rickteuthof** [comment]
How is the main of the user compiler meant to call the phase driver? In my own version it called the start function with the root phase, but since we use the generic phase driver, i'm not sure how to use that one.

**Comment by leegbestand** [comment]
There is an example on the merge_phase_driver branch in example. 
Currently, it is:
 ccn_phase_driver_init();
 ccn_phase_driver_start();
 ccn_phase_driver_destroy();

**Comment by rickteuthof** [comment]
Understood, issue is resolved. Some restructuring of files could be desirable since pass functions are now a bit lonely in actions_core.c
