### ISSUE TITLE
Add original, lowercase and uppercase name to entities 

### ISSUE THREAD

**Issue by leegbestand** [leegbestand/coconut#9]

**Comment by rickteuthof** [comment]
We could implement this by replacing each char* id of each entity by a struct containing the original, uppercase and lowercase ids, and then adding a `.upper` for example to each id in the code.

I can implement this today if you agree with this idea.

**Comment by leegbestand** [comment]
Sounds good!

**Comment by rickteuthof** [comment]
Added the implementation to new_dir_struct, will merge this with master when done.
